// Compile a workflow graph into a preview of the runtime project it deploys as.
//
// Turns the portal's node/edge graph into the files the
// `azurefunctions-agents-runtime` expects — `*.agent.md`, `tools/*.py`,
// `skills/<name>/SKILL.md`, `mcp.json`, `agents.config.yaml`, `host.json`. Used
// both for the builder's read-only "Project files" view and as the artifact the
// deployer ships. Pure and side-effect free: (doc) -> { path: contents }.

function yamlList(items) {
  if (!items || items.length === 0) return '[]'
  return `[${items.map((i) => JSON.stringify(i)).join(', ')}]`
}

function triggerFrontmatter(node) {
  const c = node.config || {}
  const map = {
    httpTrigger: () => `trigger:\n  type: http_trigger\n  args:\n    route: ${c.route || 'run'}\n    methods: ${yamlList(c.methods || ['POST'])}`,
    timerTrigger: () => `trigger:\n  type: timer_trigger\n  args:\n    schedule: "${c.schedule || '0 0 8 * * *'}"`,
    connectorTrigger: () => `trigger:\n  type: connector_trigger\n  args:\n    connector: ${c.connector || 'outlook'}\n    event: ${c.event || 'messageReceived'}`,
    queueTrigger: () => `trigger:\n  type: queue_trigger\n  args:\n    queue: ${c.queue || 'jobs'}`,
    serviceBusTrigger: () => `trigger:\n  type: service_bus_trigger\n  args:\n    queue: ${c.queue || 'incoming'}`,
    blobTrigger: () => `trigger:\n  type: blob_trigger\n  args:\n    path: ${c.path || 'incoming/{name}'}`,
    eventHubTrigger: () => `trigger:\n  type: event_hub_trigger\n  args:\n    event_hub: ${c.eventHub || 'events'}`,
    cosmosDBTrigger: () => `trigger:\n  type: cosmos_db_trigger\n  args:\n    container: ${c.container || 'items'}`,
  }
  return (map[node.kind] || map.httpTrigger)()
}

// Find the trigger node that feeds a given agent (nearest upstream trigger).
function triggerForAgent(doc, agentId) {
  const byId = new Map(doc.nodes.map((n) => [n.id, n]))
  const incoming = doc.edges.filter((e) => e.to === agentId)
  for (const e of incoming) {
    const src = byId.get(e.from)
    if (src?.type === 'trigger') return src
  }
  // Fall back to the single trigger if the graph is linear.
  return doc.nodes.find((n) => n.type === 'trigger') || null
}

function agentMarkdown(doc, agent) {
  const c = agent.config || {}
  const trigger = triggerForAgent(doc, agent.id)
  const fm = ['---', `name: ${agent.name}`]
  if (c.skills?.length) fm.push(`skills: ${yamlList(c.skills)}`)
  if (c.tools?.length) fm.push(`tools: ${yamlList(c.tools)}`)
  if (c.builtinEndpoints) fm.push('builtin_endpoints: true')
  if (c.workflows) fm.push('workflows:\n  enabled: true')
  // Only the entry agent (fed directly by the trigger) carries the trigger block.
  if (trigger && doc.edges.some((e) => e.from === trigger.id && e.to === agent.id)) {
    fm.push(triggerFrontmatter(trigger))
  }
  fm.push('---', '', c.instructions || 'You are a helpful agent.')
  return fm.join('\n') + '\n'
}

export function compileWorkflow(doc) {
  const files = {}
  const agents = doc.nodes.filter((n) => n.type === 'agent')
  const tools = doc.nodes.filter((n) => n.type === 'tool')
  const skills = doc.nodes.filter((n) => n.type === 'skill')
  const mcps = doc.nodes.filter((n) => n.type === 'mcp')

  for (const agent of agents) {
    const file = (agent.config?.sourceFile || `${agent.name.toLowerCase().replace(/[^a-z0-9]+/g, '_')}.agent.md`)
    files[file] = agentMarkdown(doc, agent)
  }
  if (agents.length === 0) {
    files['main.agent.md'] = `---\nname: ${doc.name}\n---\n\nDescribe the agent's behavior here.\n`
  }

  if (tools.length) {
    files['tools/tools.py'] =
      'from azure_functions_agents import tool\n\n\n' +
      tools.map((t) => (t.config?.code || `@tool\n${t.config?.signature || 'def tool(): ...'}`)).join('\n\n\n') +
      '\n'
  }

  for (const s of skills) {
    const name = (s.name || 'skill').toLowerCase().replace(/[^a-z0-9]+/g, '-')
    files[`skills/${name}/SKILL.md`] = `---\nname: ${s.name}\n---\n\n${s.config?.summary || 'Domain knowledge.'}\n`
  }

  if (mcps.length) {
    files['mcp.json'] = JSON.stringify(
      { servers: Object.fromEntries(mcps.map((m) => [m.config?.server || m.name, { url: m.config?.url || '' }])) },
      null,
      2,
    ) + '\n'
  }

  const globalModel = doc.target?.model || '$FOUNDRY_MODEL'
  files['agents.config.yaml'] = `# Generated by the Workflow Composer for ${doc.name}\nmodel: ${globalModel}\ntimeout: 900\n`
  files['host.json'] = JSON.stringify(
    { version: '2.0', extensions: { http: { routePrefix: '' } }, extensionBundle: { id: 'Microsoft.Azure.Functions.ExtensionBundle', version: '[4.*, 5.0.0)' } },
    null,
    2,
  ) + '\n'

  return files
}
